version: 2

jobs:
    build:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan
    versioning:
      docker:
        - image: python:latest
      steps:
        - checkout
        - run:
            name: Bumping version and tag
            command: |
              git config user.email "marceloventura@outlook.com"
              git config user.name "Marcelo Ventura"
              pip install --upgrade bump2version
              bump2version minor
              git push
              git push --tags
    deploy:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run: 
            name: tf dev workspace
            command: |
              cd terraform/
              terraform workspace select dev || terraform workspace new dev 
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan
        - run:
            name: tf apply 
            command: |
              cd terraform/
              terraform apply --auto-approve
    promote:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run: 
            name: tf qa workspace
            command: |
              cd terraform/
              terraform workspace select qa || terraform workspace new qa 
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan
        - run:
            name: tf apply 
            command: |
              cd terraform/
              terraform apply --auto-approve
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - approve:
          type: approval
          requires:
            - deploy
      - promote:
          requires:
            - approve
      - versioning:
          requires:
            - approve