version: 2

jobs:
    build:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan

    versioning:
      docker:
        - image: python:latest
      steps:
        - checkout
        - run:
            name: Bumping version and tag
            command: |
              git config user.email "marceloventura@outlook.com"
              git config user.name "Marcelo Ventura"
              pip install --upgrade bump2version
              bump2version minor
              git push
              git push --tags

    deploy_feature:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run: 
            name: tf dev workspace
            command: |
              cd terraform/
              terraform workspace select $CIRCLE_BRANCH || terraform workspace new $CIRCLE_BRANCH 
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan
        - run:
            name: tf apply 
            command: |
              cd terraform/
              terraform apply --auto-approve

    deploy_dev:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run: 
            name: tf dev workspace
            command: |
              cd terraform/
              terraform workspace select dev || terraform workspace new dev 
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan
        - run:
            name: tf apply 
            command: |
              cd terraform/
              terraform apply --auto-approve
              
    deploy_qa:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run: 
            name: tf qa workspace
            command: |
              cd terraform/
              terraform workspace select qa || terraform workspace new qa 
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan
        - run:
            name: tf apply 
            command: |
              cd terraform/
              terraform apply --auto-approve

    destroy:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run: 
            name: tf dev workspace
            command: |
              cd terraform/
              terraform workspace select $CIRCLE_BRANCH || terraform workspace new $CIRCLE_BRANCH 
        - run: 
            name: tf destroy
            command: |
              cd terraform/
              terraform destroy --auto-approve
        - run:
            name: tf workspace delete
            command: |
              cd terraform/
              terraform workspace delete $CIRCLE_BRANCH 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy_feature:
          requires:
            - build
      - approve_delete:
          type: approval
          requires:
            - deploy_feature
      - destroy:
          requires:
            - approve_delete

  build_and_release:
    jobs:
      - build:  
          filters:
            branches:
              only: master
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only: master
      - approve_promotion:
          type: approval
          requires:
            - deploy_dev
      - deploy_qa:
          requires:
            - approve_promotion
      - versioning:
          requires:
            - approve_promotion
