version: 2

jobs:
    build:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan
    deploy:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run: 
            name: tf dev workspace
            command: |
              cd terraform/
              terraform workspace select dev || terraform workspace new dev 
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan
        - run:
            name: tf apply 
            command: |
              cd terraform/
              terraform apply --auto-approve
        - run:
            name: version
            command: |
              apk update
              apk add python-pip
              pip install --upgrade bump2version
              bump2version --tag-name 'dev-v{new_version}' patch
    deploy_qa:
      docker:
        - image: hashicorp/terraform:light
      steps:
        - checkout
        - run:
            name: tf format
            command: |
              cd terraform/
              terraform fmt
        - run: 
            name: tf init
            command: |
              cd terraform/
              terraform init
        - run: 
            name: tf qa workspace
            command: |
              cd terraform/
              terraform workspace select qa || terraform workspace new qa 
        - run:
            name: tf plan
            command: |
              cd terraform/
              terraform plan -out=plan.tfplan
        - run:
            name: tf apply 
            command: |
              cd terraform/
              terraform apply --auto-approve
        - run:
            name: version
            command: |
              apk update
              apk add python-pip
              pip install --upgrade bump2version
              bump2version --tag-name 'staging-v{new_version}' minor 
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - promote?:
          type: approval
          requires:
            - deploy
      - deploy_qa:
          requires:
            - promote?